
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    ports:
      - "${MOODLE_HTTP_PORT}:8080"
      - "${MOODLE_HTTPS_PORT}:8443"
    depends_on:
      - mariadb
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${DB_USER}
      - MOODLE_DATABASE_NAME=${DB_NAME}
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
    volumes:
      - moodle_data:/bitnami/moodle

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodle_data:
